# Generated by Django 2.2 on 2021-02-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('cover_image', models.ImageField(upload_to='')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['published_date'],
            },
        ),
    ]
